### ISSUE TITLE
App fails to request internet permissions.

### ISSUE THREAD

**Issue by ghost** [sohsatoh/ReProvision-Reborn_old#12]
**Describe the bug**
The app fails to request internet permissions, instead failing with a no internet error on first request.

**To Reproduce**
1. Install the app on a device that never had it before.
2. Try entering your apple id and password
3. See error -1009

**Expected behavior**
A popup should appear asking if the user wants to allow it to access the network. Then the app should log into the apple id and perform it's function.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version 14.3
- Device - iPhone X

**Additional context**
This may be tricky to reproduce if the device ever had the app installed before. Try restoring ios, or changing the bundle id.

**Comment by sohsatoh** [comment]
Thank you. This issue has been resolved in the next v0.6.2.
(If you have any problems with v0.6.2 after its release, please open an issue again)
