### ISSUE TITLE
Error when signing AltStore

### ISSUE THREAD

**Issue by leandroprz** [sohsatoh/ReProvision-Reborn_old#14]
**Describe the bug**
ReProvision returns an error when trying to sign AltStore: https://i.ibb.co/5cRWhNH/IMG-7683.jpg

**To Reproduce**
1. Install AltStore using AltServer.
2. Install unc0ver using AltStore.
3. Install ReProvision Reborn.
4. Revoke AltStore certificate using ReProvision Reborn.
5. Sign AltStore and unc0ver using ReProvision Reborn.
6. You should get this error only for AltStore (unc0ver signs fine): https://i.ibb.co/5cRWhNH/IMG-7683.jpg

**Expected behavior**
I expected to get AltStore signed correctly.

**Screenshots**
This is my only certificate at the moment of signing AltStore and unc0ver: https://i.ibb.co/7tWmG4p/IMG-7684.jpg

**Device**
 - iOS 14.3
- iPhone 6s

**Additional context**
I know I don't really need AltStore when using ReProvision Reborn, but it seems strange to me that ReProvision Reborn returns an error when trying to sign it.

**Comment by TheRealKeto** [comment]
You're not supposed to sign AltStore with ReProvision Reborn. I suggest sticking to using one service rather than both at the same time. Your issue won't be fixed, since ReProvision Reborn is not meant to keep your AltStore app signed.

**Comment by leandroprz** [comment]
I understand. I got rid of AltStore a while ago and been using ReProvision alone, no more issues.
