### ISSUE TITLE
iOS 14.5+ & 15.0+ support

### ISSUE THREAD

**Issue by ghost** [sohsatoh/ReProvision-Reborn_old#22]
**Describe the issue**
Apple changed the code signature format in iOS 14.5 (with the same format used up to 14.7), and again in iOS 15.0 beta, so apps signed with ReProvision Reborn will no longer work. The latter may be a bit harder to test as there's currently no iOS 15 jailbreak, but AltStore has implemented support for both already.

I may attempt to do this myself, but I don't have a Mac to build the tweak, so someone else would have to test my changes.

**Comment by sohsatoh** [comment]
Sorry for the late reply.
I have a Mac so I can test it.

**Comment by sohsatoh** [comment]
I just pushed an update to support iOS14.5+
(Commit: 6908a110be94914e703ef308405bc32ff59364b1)
