### ISSUE TITLE
Consider checking the issuer_name_hash to pick the right intermediate certificate

### ISSUE THREAD

**Issue by ghost** [sohsatoh/ReProvision-Reborn_old#5]
ReProvision Reborn may cause signed apps to crash in jailed state for a minority of people who were still using an old certificate from before Jan 28 with ReProvision if they don't revoke it before resigning. (I believe this should only affect paid developer certificates as the free ones expire in 7 days, but I'm not sure if the actual certificate expires that soon for free accounts or just the provisioning profile.) I made a patch at Matchstic#178 that accounts for this case, but I don't have a Mac so I wasn't able to compile it to test. You should consider incorporating it into your code.

**Comment by ghost** [comment]
I hate smartass bots like this, I'm not a noob who is unable to follow instructions, but it was pointless to follow the template when it's a more targeted suggestion with a fix included. My issue already has all the necessary details, I was just too lazy to PR it again to this repo.

**Comment by sohsatoh** [comment]
@nyuszika7h Sorry, but I don't want to flood it with shitty issues like the original ReProvision repository.
I will look into it, thanks:)

**Comment by sohsatoh** [comment]
Implemented in https://github.com/sohsatoh/ReProvision-Reborn/commit/ab6042ea578dcf8a8f10601a36a3952b08aa3730
